
project:
  type: website
  output-dir: _site
  render:
    - "!x-*.qmd"
    - "00-import-clean-penguins.qmd"
    - "index.qmd"

website:
  title: "Quarto R GitHub Pages Starter"
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/bonanastasia/quarto_r_github_pages_starter
    contents:
      - text: "Home"
        href: index.qmd
      - auto: "*.qmd"   

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: paged
    code-overflow: wrap