
project:
  type: website
  output-dir: _site

website:
  title: "Quarto R GitHub Pages Starter"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01-analysis.qmd
        text: Analysis

format:
  html:
    theme: cosmo
    toc: true
    code-overflow: wrap
