
name: Publish Quarto Website

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c('tidyverse', 'palmerpenguins', 'rmarkdown', 'knitr', 'quarto'))"

      - uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto project
        run: quarto render

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
